/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmSideDrawer {
        "open": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLAmSideDrawerElement extends Components.AmSideDrawer, HTMLStencilElement {
    }
    var HTMLAmSideDrawerElement: {
        prototype: HTMLAmSideDrawerElement;
        new (): HTMLAmSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "am-side-drawer": HTMLAmSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface AmSideDrawer {
        "open"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "am-side-drawer": AmSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "am-side-drawer": LocalJSX.AmSideDrawer & JSXBase.HTMLAttributes<HTMLAmSideDrawerElement>;
        }
    }
}
